definitions:
  config:
    /hippo:configuration/hippo:userroles/xm.config-editor.current-page.editor:
      jcr:primaryType: hipposys:userrole
      hipposys:description: Required to make changes in the Channel Config Editor plugin's Current Page tab
      hipposys:system: true
      hipposys:userroles: [xm.config-editor.current-page.viewer]
