definitions:
  config:
    /hippo:configuration/hippo:domains/channelConfigEditor:
      jcr:primaryType: hipposys:domain
      /readonly:
        jcr:primaryType: hipposys:authrole
        hipposys:groups:
          .meta:category: system
          .meta:add-new-system-values: true
          operation: override
          type: string
          value: []
        hipposys:role: readonly
        hipposys:userrole:
          .meta:category: system
          type: string
          value: xm.config-editor.user
        hipposys:users:
          .meta:category: system
          .meta:add-new-system-values: true
          operation: override
          type: string
          value: []
      /config-editor-extension:
        jcr:primaryType: hipposys:domainrule
        /extension-and-descendants:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:path
          hipposys:type: Reference
          hipposys:value: /hippo:configuration/hippo:frontend/cms/ui-extensions/channelConfigEditor
