definitions:
  config:
    /hst:hst/hst:hosts/dev-localhost:
      .meta:residual-child-node-category: content
      jcr:primaryType: hst:virtualhostgroup
      hst:defaultport: 8080
      /localhost:
        .meta:residual-child-node-category: content
        jcr:primaryType: hst:virtualhost
        /hst:root:
          .meta:residual-child-node-category: content
          jcr:primaryType: hst:mount
          hst:homepage: root
          hst:mountpoint: /hst:channelconfigeditordemo/hst:sites/channelconfigeditordemo
          hst:responseheaders: ['Access-Control-Allow-Origin: *', 'Access-Control-Allow-Credentials:
              true']
          hst:pagemodelapi: resourceapi
          /fr:
            .meta:residual-child-node-category: content
            jcr:primaryType: hst:mount
            hst:mountpoint: /hst:channelconfigeditordemo/hst:sites/channelconfigeditordemo-fr
            hst:locale: fr_FR
