/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * the components that are defined in the current page
 * @export
 * @interface AbstractComponent
 */
export interface AbstractComponent {
    /**
     * identifying name of this component within its page
     * @type {string}
     * @memberof AbstractComponent
     */
    name: string;
    /**
     * description for this component
     * @type {string}
     * @memberof AbstractComponent
     */
    description?: string | null;
    /**
     * a map of string parameters (names/values) for this component
     * @type {{ [key, string]: string;}}
     * @memberof AbstractComponent
     */
    parameters?:  any;
    /**
     * the layout used for rendering inner containers
     * @type {string}
     * @memberof AbstractComponent
     */
    xtype?: AbstractComponentXtypeEnum;
    /**
     * the type of this component
     * @type {string}
     * @memberof AbstractComponent
     */
    type: AbstractComponentTypeEnum;

    /**
     * the components that are defined in the current page
     * @type {Array&lt;AbstractComponent&gt;}
     * @memberof Page
     */
    components?: Array<AbstractComponent>;
}

/**
    * @export
    * @enum {string}
    */
export enum AbstractComponentXtypeEnum {
    Vbox = 'hst.vbox',
    Unorderedlist = 'hst.unorderedlist',
    Orderedlist = 'hst.orderedlist',
    Span = 'hst.span',
    Nomarkup = 'hst.nomarkup'
}
/**
    * @export
    * @enum {string}
    */
export enum AbstractComponentTypeEnum {
    Static = 'static',
    Managed = 'managed'
}

