/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CatalogGroup
 */
export interface CatalogGroup {
    /**
     * identifying name of a catalog group for its channel; \"base\" is a reserved and predefined (system) group name
     * @type {string}
     * @memberof CatalogGroup
     */
    name: string;
    /**
     * indicator if this catalog group (and its resources, e.g. components) will be available in the ChannelManager UI
     * @type {boolean}
     * @memberof CatalogGroup
     */
    hidden?: boolean;
    /**
     * indicator if this catalog group (and its resources, e.g. components) are protected; if true implies hidden is true
     * @type {boolean}
     * @memberof CatalogGroup
     */
    system?: boolean;
}
