/* tslint:disable */
/* eslint-disable */

/**
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface Channel
 */
export interface Channel {
  /**
   * identifier for a specific channel branch; constructed as \"<channel name>:<channel branch>\"
   * @type {string}
   * @memberof Channel
   */
  id?: string;
  /**
   * identifying name of a channel
   * @type {string}
   * @memberof Channel
   */
  name: string;
  /**
   * name of the channel branch
   * @type {string}
   * @memberof Channel
   */
  branch?: string | null;
  /**
   * name of channel branch this branch is branched from (if branched), currently always 'master'
   * @type {string}
   * @memberof Channel
   */
  branchOf?: string | null;
  /**
   * the (repository) content path (as child of /content) to be used as base content path for this channel; cannot be
   * (only) /
   * @type {string}
   * @memberof Channel
   */
  contentRootPath: string | null;
  /**
   * (content) locale to be used and assumed for this channel
   * @type {string}
   * @memberof Channel
   */
  locale?: string | null;
  /**
   * names and width of supported delivery tier 'devices' to choose from for the Channel Manager (preview) rendering
   * @type {Array&lt;string&gt;}
   * @memberof Channel
   */
  devices?: Array<string>;
  /**
   * name of the default 'device' to use by default for the Channel Manager (preview) rendering, defaults to
   * \"default\" if not configured
   * @type {string}
   * @memberof Channel
   */
  defaultDevice?: string | null;
  /**
   * optional response headers to provide on a (PMA) response
   * @type {{ [key, string]: string;}}
   * @memberof Channel
   */
  responseHeaders?: any | null;
  /**
   * The prefix to prepend to links when the Channel PMA is accessed through a reverse proxy
   * @type {string}
   * @memberof Channel
   */
  linkurlPrefix?: string | null;
  /**
   * The CDN to use (where applicable and possible)
   * @type {string}
   * @memberof Channel
   */
  cdnHost?: string | null;
  /**
   * a map of parameters (names/values) for this Channel
   * @type {{ [key, string]: any;}}
   * @memberof Channel
   */
  parameters?: any;
}
