/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ComponentDefinition
 */
export interface ComponentDefinition {
    /**
     * identifier of this component definition: {group}/{name}
     * @type {string}
     * @memberof ComponentDefinition
     */
    id: any;
    /**
     * {group}/{name} id of the component definition this definition extends from
     * @type {string}
     * @memberof ComponentDefinition
     */
    _extends: any;
    /**
     * indicator if this component definition is configurable in the ChannelManager UI
     * @type {boolean}
     * @memberof ComponentDefinition
     */
    hidden?: any;
    /**
     * indicator if this a protected (system) component definition; if true, implies hidden is true
     * @type {boolean}
     * @memberof ComponentDefinition
     */
    system?: any;
    /**
     * frontend layout type
     * @type {string}
     * @memberof ComponentDefinition
     */
    xtype?: any;
    /**
     * frontend component type
     * @type {string}
     * @memberof ComponentDefinition
     */
    ctype?: any;
    /**
     * default display name of this component definition in the ChannelManager UI
     * @type {string}
     * @memberof ComponentDefinition
     */
    label?: any;
    /**
     * base64 representation of the icon for this component definition in the ChannelManager UI
     * @type {string}
     * @memberof ComponentDefinition
     */
    icon?: any;
    /**
     * custom (residual) or customized (overlaying) parameters for this component definition
     * @type {Array&lt;ParameterType&gt;}
     * @memberof ComponentDefinition
     */
    parameters?: any;
    /**
     * field groups
     * @type {Array&lt;FieldGroup&gt;}
     * @memberof ComponentDefinition
     */
    fieldGroups?: any;
}
