/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface DevelopmentConfig
 */
export interface DevelopmentConfig {
    /**
     * name of the development configuration
     * @type {string}
     * @memberof DevelopmentConfig
     */
    name: any;
    /**
     * a map of development configuration parameters (names/values)
     * @type {{ [key, string]: string;}}
     * @memberof DevelopmentConfig
     */
    parameters?: any;
}
