/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {AbstractComponent} from "./abstract-component";

/**
 * 
 * @export
 * @interface ManagedComponent
 */
export interface ManagedComponent extends AbstractComponent {
    /**
     * default display label for this component
     * @type {string}
     * @memberof ManagedComponent
     */
    label?: string;
}


