/* tslint:disable */
/* eslint-disable */

/**
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {AbstractComponent} from "./abstract-component";
import {Nullable} from "./nullable";

/**
 *
 * @export
 * @interface Page
 */
export interface Page {
  /**
   * identifying name of this page within its channel
   * @type {string}
   * @memberof Page
   */
  name: string | null;
  /**
   * description for this page
   * @type {string}
   * @memberof Page
   */
  description?: string | null;
  /**
   * a map of string parameters (names/values) for this page
   * @type {{ [key, string]: string;}}
   * @memberof Page
   */
  parameters?:  [string, any] | {};
  /**
   * page type defines the usage. Only abstract pages can be extended. Valid values: abstract, page, xpage
   * @type {string}
   * @memberof Page
   */
  type: string;
  // type: PageTypeEnum ;
  /**
   * the name of the (abstract) page extended by this page
   * @type {string}
   * @memberof Page
   */
  extends?: Nullable<string>

  /**
   * the components that are defined in the current page
   * @type {Array&lt;AbstractComponent&gt;}
   * @memberof Page
   */
  components?: Nullable<Array<AbstractComponent>>;
  // components?: Array<AbstractComponent>;

}

