/* tslint:disable */
/* eslint-disable */

/**
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Page
 */
export interface Page {
  /**
   * identifying name of this page within its channel
   * @type {string}
   * @memberof Page
   */
  name: string;
  /**
   * description for this page
   * @type {string}
   * @memberof Page
   */
  description?: string;
  /**
   * a map of string parameters (names/values) for this page
   * @type {{ [key, string]: string;}}
   * @memberof Page
   */
  parameters?: Array<{key: string, value: string}>;
  /**
   * page type defines the usage. Only abstract pages can be extended. Valid values: abstract, page, xpage
   * @type {string}
   * @memberof Page
   */
  type: PageTypeEnum;
  /**
   * the name of the (abstract) page extended by this page
   * @type {string}
   * @memberof Page
   */
  _extends?: string;

}

/**
 * @export
 * @enum {string}
 */
export enum PageTypeEnum {
  Abstract = 'abstract',
  Page = 'page',
  Xpage = 'xpage'
}

