/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Field Config
 * @export
 * @interface ParameterConfigType
 */
export interface ParameterConfigType {
    /**
     * the type of this config field
     * @type {string}
     * @memberof ParameterConfigType
     */
    type: ParameterConfigTypeTypeEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum ParameterConfigTypeTypeEnum {
    Contentpath = 'contentpath',
    Dropdown = 'dropdown',
    Imagesetpath = 'imagesetpath'
}

