/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {ParameterConfigType} from "./parameter-config-type";

/**
 *
 * @export
 * @interface ParameterContentPathType
 */
export interface ParameterContentPathType extends ParameterConfigType {
  /**
   *
   * @type {string}
   * @memberof ParameterContentPathType
   */
  pickerConfiguration?: string;
  /**
   *
   * @type {string}
   * @memberof ParameterContentPathType
   */
  pickerInitialPath?: string;
  /**
   *
   * @type {boolean}
   * @memberof ParameterContentPathType
   */
  pickerRememberLastVisited?: boolean;
  /**
   *
   * @type {Array&lt;string&gt;}
   * @memberof ParameterContentPathType
   */
  pickerSelectableNodeTypes?: Array<string>;
  /**
   *
   * @type {boolean}
   * @memberof ParameterContentPathType
   */
  relative?: boolean;
  /**
   *
   * @type {string}
   * @memberof ParameterContentPathType
   */
  pickerRootPath?: string;
}


