/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {ParameterConfigType} from "./parameter-config-type";

/**
 * 
 * @export
 * @interface ParameterDropdownType
 */
export interface ParameterDropdownType extends ParameterConfigType {
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof ParameterDropdownType
     */
    value: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ParameterDropdownType
     */
    valueListProvider: string ;
    /**
     * 
     * @type {string}
     * @memberof ParameterDropdownType
     */
    sourceId: string;
}


