/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {Nullable} from "./nullable";

/**
 * the components that are defined in the current page
 * @export
 * @interface AbstractComponent
 */
export interface AbstractComponent {
  /**
   * identifying name of this component within its page
   * @type {string}
   * @memberof AbstractComponent
   */
  name: string;
  /**
   * description for this component
   * @type {string}
   * @memberof AbstractComponent
   */
  description?: Nullable<string>
  /**
   * a map of string parameters (names/values) for this component
   * @type {{ [key, string]: string;}}
   * @memberof AbstractComponent
   */
  parameters?: any;
  /**
   * the layout used for rendering inner containers
   * @type {string}
   * @memberof AbstractComponent
   */
  xtype?: Nullable<string>;
  /**
   * the type of this component
   * @type {string}
   * @memberof AbstractComponent
   */
  type: Nullable<string>;

  /**
   * the components that are defined in the current page
   * @type {Array&lt;AbstractComponent&gt;}
   * @memberof Page
   */
  components?: Nullable<Array<AbstractComponent>>;

  /**
   * default display label for this component
   * @type {string}
   * @memberof ManagedComponent
   */
  label?: Nullable<string>;

  /**
   * the catalog component definition this component is based on
   * @type {string}
   * @memberof StaticComponent
   */
  definition?: Nullable<string>;


}