/* tslint:disable */
/* eslint-disable */

/**
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {AbstractComponent} from "./abstract-component";
import {Nullable} from "./nullable";

/**
 *
 * @export
 * @interface Page
 */
export interface Page extends AbstractComponent{

  /**
   * the name of the (abstract) page extended by this page
   * @type {string}
   * @memberof Page
   */
  extends?: Nullable<string>

}

