/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {AbstractComponent} from "./abstract-component";

/**
 *
 * @export
 * @interface StaticComponent
 */
export interface StaticComponent extends AbstractComponent {
  /**
   * the catalog component definition this component is based on
   * @type {string}
   * @memberof StaticComponent
   */
  definition?: string;
}


